name: Build OpenWrt for OpenWrt (Default - GL-MT1300 (Beryl))

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      TARGET_ARCHITECTURE:
        description: 'Target architecture for the build'
        default: 'ramips'
        required: true
      TARGET_VARIANT:
        description: 'Target variant for the build'
        default: 'mt7621'
        required: true
      TARGET_DEVICE:
        description: 'Target device profile for the build'
        default: 'glinet_gl-mt1300'
        required: true

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget rsync xz-utils build-essential libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils

      - name: Build OpenWrt firmware
        run: |
          # Fetch input parameters or use defaults
          TARGET_ARCHITECTURE="${{ github.event.inputs.TARGET_ARCHITECTURE }}"
          TARGET_VARIANT="${{ github.event.inputs.TARGET_VARIANT }}"
          TARGET_DEVICE="${{ github.event.inputs.TARGET_DEVICE }}"
          
          # Call the renamed bash script with parameters
          chmod +x ./build.sh
          ./build.sh $TARGET_ARCHITECTURE $TARGET_VARIANT $TARGET_DEVICE

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-${{ github.event.inputs.TARGET_DEVICE }}
          path: ./build/openwrt-imagebuilder-*/bin/targets/${{ github.event.inputs.TARGET_ARCHITECTURE }}/
